# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - prime-wordpress

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_b7b4aabab5cd4a5b89c77a7448c3cd1d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d762b00a611a49daa2448b0efaaf2bc4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_b7b4aabab5cd4a5b89c77a7448c3cd1d }}/appsvc/wordpress-alpine-php:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'prime-wordpress'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_55aa8c855eff4e28aa3005822100b829 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_b7b4aabab5cd4a5b89c77a7448c3cd1d }}/appsvc/wordpress-alpine-php:${{ github.sha }}'